.TH E2MV 1 "2020\-02\-05" "Linux" "User commands"
.\"
.SH NAME
e2mv \- moves or renames files on an ext2fs filesystem
.\"
.SH SYNOPSIS
.B e2mv
.RI [ options ] " files... dest"
.\"
.SH DESCRIPTION
The \fBe2mv\fP command moves or renames files on an ext2fs filesystem. The
source files must be explicitly stated. It does not use regular expressions,
yet.
.\"
.SH OPTIONS
.TP
.B \-f
Force the operation to remove any existing files.
.TP
.B \-s
Swap names of the two files.
.TP
.B \-v
Be verbose.
.\"
.SH EXAMPLES
.PP
Rename a file:

    e2cp \-v /tmp/boot.img:/boot/grub/grub.conf /boot/grub/grub.conf.old
.\"
.PP
If `/boot/grub/grub.conf.old` already exists and is not a directory, this
will fail.  Use `\-f` to force removal.
.PP
Move a file to a different directory (`/data/processed`):

    e2cp \-v /dev/hdb1:/data/input0.txt /data/processed
.\"
.PP
To swap the names of two files:

    e2cp \-vs /tmp/boot.img:/boot/grub/grub.conf /boot/grub/grub.conf.bk
.\"
.PP
To swap two files and use a new name for the first one:

    e2cp \-vs boot.img:/boot/grub/grub.conf /boot/grub/grub.c2 /boot/grub/grub.c1

    `/boot/grub/grub.conf` is now `/boot/grub/grub.c1` and
    `/boot/grub/grub.c2`   is now `/boot/grub/grub.conf`
.\"
.SH SEE ALSO
.BR e2tools (7),
.BR e2ln (1),
.BR e2ls (1),
.BR e2mkdir (1),
.BR e2cp (1),
.BR e2rm (1),
.BR e2tail (1).
.\"
.SH AUTHOR
The \fBe2tools\fP were written by Keith Sheffield <sheff@pobox.com>.
.PP
This manual page was written by Lucas Wall <lwall@debian.org>,
for the Debian project (but may be used by others).
